version: "3.7"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14250:14250"
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger
  postgres:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    image: postgres:13.1
    logging:
      options:
        max-file: "3"
        max-size: 10m
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgre:/docker-entrypoint-initdb.d/
volumes:
  certs:
  logs:
  fallbackcerts: